### ISSUE TITLE
Two different DAB

### ISSUE THREAD

**Issue by jingdu-cs** [ifiaposto/Distance_Aware_Bottleneck#1]
Hi, 

Thank you for sharing your codebase, it's really helpful!

I noticed that two different functions are used for different tasks: 
`NormalFullCovarianceDAB` is used for ImageNet while `NormalDiagCovarianceDAB` is used for CIFAR and synthetic datasets. Could you please explain the differences between `NormalDiagCovarianceDAB` and `NormalFullCovarianceDAB`? Why different functions are used for different tasks?

Thank you very much for your answer!

Best, Jing

**Comment by ifiaposto** [comment]
Hi!

Thanks for your question. NormalDiagCovarianceDAB uses a diagonal covariance matrix for the Gaussians while NormalFullCovarianceDAB uses a full covariance matrix for the Gaussians (along with some precomputations to optimize the code). The first is more suitable for high-dimensional distributions needed for larger-scale experiments like ImageNet.  You can also see tensorflow's probability [full covariance](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/MultivariateNormalFullCovariance ) vs [diagonal covariance](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/MultivariateNormalDiag) Gaussian distributions used by the code for more details. Please let me know if this is still unclear.

Best regards,

Ifigeneia
